name: miraapp
description: "MiraApp, qr scanner per gli edifici storici, di gus45"
publish_to: 'none'
version: 2.2.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.3
  image: ^4.7.2
  mobile_scanner: ^5.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  url_launcher: ^6.2.5
  audioplayers: ^5.2.1
  webview_flutter: ^4.4.2
  flutter_launcher_icons: ^0.14.4
  camera_desktop: ^1.0.6
  package_info_plus: ^8.0.0
  tflite_flutter: ^0.12.1




flutter:
  uses-material-design: true
  assets:
    - assets/model_unquant.tflite
    - assets/labels.txt
    - assets/images/
    - assets/audio/
    - assets/icon/
